// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMeeHbZH0ZpOVqQibcrjsLXkn34kc8lYw',
    appId: '1:1043465103826:web:bb095cd2011e3dcf8b000b',
    messagingSenderId: '1043465103826',
    projectId: 'groww-76135',
    authDomain: 'groww-76135.firebaseapp.com',
    storageBucket: 'groww-76135.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtHSGKrLhPb0zr4e9Zls8J3DoDZ09Pc7k',
    appId: '1:1043465103826:android:ca39316b45548f508b000b',
    messagingSenderId: '1043465103826',
    projectId: 'groww-76135',
    storageBucket: 'groww-76135.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI0YvGvfL-dYUcloRo6TYA2gtE5T89SGY',
    appId: '1:1043465103826:ios:6963d1f935db2f878b000b',
    messagingSenderId: '1043465103826',
    projectId: 'groww-76135',
    storageBucket: 'groww-76135.appspot.com',
    iosClientId: '1043465103826-1432asjva39hn5bn2sfra22fbpbbqcpb.apps.googleusercontent.com',
    iosBundleId: 'com.example.growwui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI0YvGvfL-dYUcloRo6TYA2gtE5T89SGY',
    appId: '1:1043465103826:ios:6963d1f935db2f878b000b',
    messagingSenderId: '1043465103826',
    projectId: 'groww-76135',
    storageBucket: 'groww-76135.appspot.com',
    iosClientId: '1043465103826-1432asjva39hn5bn2sfra22fbpbbqcpb.apps.googleusercontent.com',
    iosBundleId: 'com.example.growwui',
  );
}
